name: EndoriaLobby
version: 1.0-SNAPSHOT
main: fr.hugob147.endorialobby.EndoriaLobby
authors: [hugob147, TinouHD]
commands:
  rank:
    description: Permet de manipuler les rank.
  ts:
    description: Affiche l'ip du TeamSpeak d'EndoriaNetwork.
    aliases: [teamspeak]
  discord:
    description: Affiche le lien d'invitation au discord d'EndoriaNetwork.
  web:
    description: Affiche le lien du site web d'EndoriaNetwork.
    aliases: [site]
  socials:
    description: Affiche tous les liens des réseaux socieaux d'EndoriaNetwork.
